{
  "env" : {
    "node": true ,
    "es6": true ,
    "browser" : false
 	},
 	"rules": {
    "strict" : 0,
    "no-console": 0 ,
    "semi": 2,
    "max-len": 0,
    "comma-dangle": ["error", "never"],
    "no-invalid-this": 0,
    "class-methods-use-this": 0,
    "no-underscore-dangle": 0
  }
}

