language: node_js
node_js:
  - "6"
  - "8"
  - "node"

dist: trusty
sudo: false
cache: yarn
script:
  - yarn run test --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
