'use strict';

module.exports = {
  BY_PER_WEEK_DAY: 0,
  BY_PER_WEEK: 1,
  BY_PER_MONTH: 2,
  BY_PER_YEAR: 3,
  BY_PER_DAY_OF_MONTH: 4,
  BY_PER_DAY_HOUR: 5,
  BY_PER_DAY_HOUR_OF_WEEK_DAY: 6,
  SUMMARY_BY_AUTHOR: 7,
  SUMMARY_BY_COMMITTER: 8
};
